telegram_token: "your_telegram_bot_token"
gemini_api_key: "your_gemini_api_key"  # کلید API جدید Gemini
allowed_telegram_usernames: []  # برای محدود کردن دسترسی (اختیاری)
new_dialog_timeout: 600  # ثانیه
enable_message_streaming: true
n_chat_modes_per_page: 5