telegram_token: "6429865327:AAEn-31ua59S9aEcvxpWtoUnGPSjz6lW1Ic"
gemini_api_key: "AIzaSyDYy1lxVwaRzNK8Lo8b1mZq5dUgo1cpQyA"  # کلید API جدید Gemini
allowed_telegram_usernames: []  # برای محدود کردن دسترسی (اختیاری)
new_dialog_timeout: 600  # ثانیه
enable_message_streaming: true
n_chat_modes_per_page: 5